//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сlients
    {
        public int idClient { get; set; }
        public Nullable<int> numberphone { get; set; }
        public string fio { get; set; }
        public string subscriber { get; set; }
        public Nullable<int> idTrainer { get; set; }
    
        public virtual Trainers Trainers { get; set; }
    }
}
